#!/bin/bash
# daily-recall.sh — Daily memory review (v2: pure RecallNest, no dependency on claude -p)
# Uses lm distill to extract structured insights from past conversations
# Rotates the query topic each day; output is saved to daily-reflections/YYYY-MM-DD.md

set -euo pipefail

# ── Path configuration ────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LM="$SCRIPT_DIR/lm"
REFLECTION_DIR="$SCRIPT_DIR/daily-reflections"
LOG_DIR="$SCRIPT_DIR/logs"
DATE=$(date '+%Y-%m-%d')
OUTPUT_FILE="$REFLECTION_DIR/$DATE.md"
LOG_FILE="$LOG_DIR/daily-recall.log"

# ── Environment variables ─────────────────────────────────────
export PATH="$HOME/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export HOME="${HOME:-/Users/anxianjingya}"

# Load .env (JINA_API_KEY, etc.)
if [ -f "$SCRIPT_DIR/.env" ]; then
  set -a
  source "$SCRIPT_DIR/.env"
  set +a
fi

# ── Prepare directories ───────────────────────────────────────
mkdir -p "$REFLECTION_DIR"
mkdir -p "$LOG_DIR"

echo "=== $(date '+%Y-%m-%d %H:%M:%S') daily-recall started ===" | tee -a "$LOG_FILE"

# ── Daily rotating queries (one full cycle every 7 days) ──────
# Query strings are kept in Chinese: they are functional inputs matched
# against the bilingual memory store; translating them would change what is retrieved.
QUERIES=(
  "成长 经历 改变了什么"
  "洞察 反思 核心教训"
  "哲学 意识 自由意志"
  "写作 表达 风格探索"
  "技术 架构 解决方案"
  "感悟 人心 被看见"
  "踩坑 修复 经验总结"
)

DOW=$(date '+%u')  # 1=Monday ... 7=Sunday
IDX=$(( (DOW - 1) % ${#QUERIES[@]} ))
TODAY_QUERY="${QUERIES[$IDX]}"

echo "  Today's topic (#$((IDX+1))): $TODAY_QUERY" | tee -a "$LOG_FILE"

# ── CC-6 + HP-3: Distill gate — lock + session gate + activity gate ─────
echo "  Checking distill gate..." | tee -a "$LOG_FILE"
GATE_RESULT=$(bun -e "
  const { acquireLock, shouldDistill } = require('./src/distill-lock.ts');
  const { getDistillTier } = require('./src/activity-counter.ts');
  const cp = parseInt(process.argv[1] || '0', 10);
  const tier = getDistillTier();
  const sessionReady = shouldDistill(cp);
  if (tier === 'none' && !sessionReady) { console.log('SKIP:no_activity'); process.exit(0); }
  if (!acquireLock()) { console.log('SKIP:lock_held'); process.exit(0); }
  console.log('OK:' + tier);
" "$(bun run "$SCRIPT_DIR/src/cli.ts" checkpoint-count 2>/dev/null || echo 5)" 2>&1 || echo "OK:standard")

if [[ "$GATE_RESULT" == SKIP:* ]]; then
  echo "  [skipped] distill gate: $GATE_RESULT" | tee -a "$LOG_FILE"
else
  echo "  distill gate: $GATE_RESULT" | tee -a "$LOG_FILE"
fi

# ── Extract structured insights with lm distill ───────────────
echo "  Running distill..." | tee -a "$LOG_FILE"
DISTILL_OUTPUT=$("$LM" distill "$TODAY_QUERY" --profile writing --limit 8 --all-scopes 2>&1 || true)

if [ -z "$DISTILL_OUTPUT" ]; then
  echo "  [warning] distill produced no output, trying export..." | tee -a "$LOG_FILE"
  DISTILL_OUTPUT=$("$LM" export "$TODAY_QUERY" --profile writing --limit 5 --format md --all-scopes 2>&1 || true)
fi

if [ -z "$DISTILL_OUTPUT" ]; then
  echo "  [error] both distill and export produced no output, aborting" | tee -a "$LOG_FILE"
  exit 1
fi

echo "  distill complete, $(echo "$DISTILL_OUTPUT" | wc -l | tr -d ' ') lines" | tee -a "$LOG_FILE"

# CC-6: Release lock on success + HP-3: Reset activity counter
bun -e "try { require('./src/distill-lock.ts').releaseLock(); } catch {}" 2>/dev/null || true
bun -e "try { require('./src/activity-counter.ts').resetWriteCount(); } catch {}" 2>/dev/null || true

# ── Write the output file ─────────────────────────────────────
cat > "$OUTPUT_FILE" << EOF
# Daily Review · $DATE

> Topic: $TODAY_QUERY

$DISTILL_OUTPUT

---
*Auto-generated by daily-recall.sh v2 · $(date '+%Y-%m-%d %H:%M:%S')*
*Engine: RecallNest distill (profile: writing)*
EOF

echo "  [done] review written to: $OUTPUT_FILE" | tee -a "$LOG_FILE"

# ── Checkpoint GC (enabled 2026-03-26) ────────────
echo "  Running checkpoint-gc..." | tee -a "$LOG_FILE"
GC_OUTPUT=$(bun run "$SCRIPT_DIR/src/cli.ts" checkpoint-gc 2>&1 || true)
echo "  checkpoint-gc: $GC_OUTPUT" | tee -a "$LOG_FILE"

echo "=== $(date '+%Y-%m-%d %H:%M:%S') daily-recall finished ===" | tee -a "$LOG_FILE"
